# Generated by Django 5.1.7 on 2025-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animation_logo',
            field=models.URLField(blank=True, help_text='URL to the animated logo/gif for the project'),
        ),
    ]
