# Generated by Django 5.1.7 on 2025-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_animation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.URLField(blank=True, help_text='URL to the skill logo'),
        ),
    ]
