# Generated by Django 5.1.7 on 2025-10-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_skill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('conference', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('abstract', models.TextField(blank=True)),
                ('paper_link', models.URLField(blank=True)),
                ('code_link', models.URLField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('impact_factor', models.CharField(blank=True, max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='portfolio_app.profile')),
            ],
        ),
    ]
